### ISSUE TITLE
File name with reserved URL characters is not supported

### ISSUE THREAD

**Issue by bratukham** [IonDen/ion.sound#31]
I got this bug when had tried to use a file with name __test#.mp3__.
Symbol __#__ should be replaced by [__%23__](https://en.wikipedia.org/wiki/Percent-encoding) to make a request to the server.

**Comment by IonDen** [comment]
Fixed in 3.0.1

**Comment by bratukham** [comment]
The bug is still here, but only for Friefox (at least in ver. 40.0.2).

The file loading goes fine:
![image](https://cloud.githubusercontent.com/assets/1413357/9428744/d5b99e34-49b8-11e5-8559-a46b847085ce.png)

But then it suddenly says that there is no such sound:
![image](https://cloud.githubusercontent.com/assets/1413357/9428745/fd908666-49b8-11e5-8723-9d9ed818aac9.png)


Any adeas?

**Comment by IonDen** [comment]
Hi, i will try o check this in the end of the week.

**Comment by a4jp-com** [comment]
I sliced away characters from my array to get the code working on a PC.

Here is a sample of my code. 

It might give you a few ideas on fixing your problem.

```
var thearray1 = Version[item[itemnumber]][3][0];

//remove last 4 characters
var withoutChars = thearray1.slice(0, -4);	

//remove first 12 characters
var withoutChars2 = withoutChars.slice(12);

ion.sound({sounds:[{name: withoutChars2}], volume: 1.0, path:"/ion/sounds/", preload: false});
ion.sound.play(encodeURIComponent(withoutChars2));
```

**Comment by a4jp-com** [comment]
Whoops. I just saw this was from a year ago. I'll keep the post here though. It might help someone.
