### ISSUE TITLE
some sounds doesn't load

### ISSUE THREAD

**Issue by micrem73** [IonDen/ion.sound#42]
Hi,

please check this simple project:  https://dl.dropboxusercontent.com/u/6974/ion.soundsbug.zip
Strangely, sounds 1, 3 and 5 plays; sounds 2, 4 and 6 doesn't.
What's wrong?

**Comment by IonDen** [comment]
Hi, this is because of sound names 1, 2, 3 etc. Fix will be ready soon. If you don't want to wait, just rename sounds to, for example, "a1", "a2", "a3" etc.

**Comment by IonDen** [comment]
Fixed in 3.0.4

**Comment by micrem73** [comment]
Thanks a lot. I upgraded to  3.0.4 but it seems not fixed yet.

**Comment by IonDen** [comment]
I tested on your demo. It was fine. Maybe cache? Bower version could still be old.

**Comment by micrem73** [comment]
right, was a cache topic. thanks.
